spring.application.name=TechGadget API
server.port=${PORT:8080}


spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.urcdaqnklopituqfqfli
spring.datasource.password=techgadget123456@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0

payos.client-id=ac2d5249-1eb8-422d-86b2-844076e2eec0
payos.api-key=935613dc-bfba-4283-bbff-78e11374c7a3
payos.checksum-key=f46df1352b1acbea670e89a6956b2f2f285b4d5f65d02952701067ad881a3ccf
payos.return-url=${PAYOS_RETURN_URL:http://localhost:3000/checkout/success}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:3000/checkout/cancel}
