spring.application.name=TechGadget API
server.port=${PORT:8086}


spring.datasource.url=jdbc:postgresql://localhost:5432/tech
spring.datasource.username=postgres
spring.datasource.password=trungkien2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0