spring.application.name=TechGadget API
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.urcdaqnklopituqfqfli.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=techgadget123456@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0